### ISSUE TITLE
Loot overlay token , numbered overlay tokens and letter overlay tokens would be great additions

### ISSUE THREAD

**Issue by gudyfr** [any2cards/frosthaven#3]

**Comment by any2cards** [comment]
The loot location icon can bee found at: art \ frosthaven \ icons \ general \ fh-loot-location-color-icon.png

I will look to see if Isaac shared the numbered and letter overlay tokens.

One other thing: please note that this repo "Frosthaven" is intended to be deprecated.  It has been replaced with the "Worldhaven" repo.

**Comment by any2cards** [comment]
All the scenario aid and number tokens have been added under:

tokens \ frosthaven \ scenario-aids

**Comment by gudyfr** [comment]
Thank you !
