### ISSUE TITLE
Any chance you would be able to upload the overlay tiles?

### ISSUE THREAD

**Issue by oddhours** [any2cards/frosthaven#4]
I'm making my own tuck boxes for cardboard storage, and I was hoping you might have the overlay tiles? I see a folder at: images\art\frosthaven\icons\overlay-tiles, but this folder just has the generic category icons, none of the specific icons.

Side note: Thank you for sharing this. This has made my project look far better than the photos I had taken with my camera!

**Comment by any2cards** [comment]
First, you should know that this repo will be eventually deprecated (with notice), as the full repo is the "Worldhaven" repo (including all Haven games in one).

None the less, if you go to: images\tokens\frosthaven\terrain, you should find all of the actual overlay tiles.  If you don't see what you need, reach out again.

**Comment by oddhours** [comment]
That is good to know, and thank you for pointing me to the correct folder.
