### ISSUE TITLE
Missing coin icon from loot icons

### ISSUE THREAD

**Issue by thejcannon** [any2cards/frosthaven#7]
:wave: Me again!

I'm also wondering if there's a chance for the coin icon to make it's way into the loot icons directory? 

Thanks!

**Comment by any2cards** [comment]
Sorry this took a bit to get back to you.  I am in the midst of an 1800 mile road trip going back home.  What exactly are you looking for?  What "coin icon" are you looking for?

**Comment by thejcannon** [comment]
That's a big road trip 😯! It's no rush, I found the icon in the rule book and since it seems to be using an svg internally I was able to scale it up and get a nice crisp image.

Specifically, the coin loot icon (found at the bottom of gold loot cards)

**Comment by any2cards** [comment]
I just realized that the Money Icon and the Treasure Chest Item Icon were in the General directory.  I have moved them to the Loot directory.  You should be able to find both there (and at higher quality than the one I previously created, due to a mistake I made).
