### ISSUE TITLE
Section book pass 100 Frosthaven

### ISSUE THREAD

**Issue by redguar** [any2cards/frosthaven#9]
Error rendering embedded code

Error loading PDF page number 2

Does not happen on rulebook, but happens on some section books

**Comment by any2cards** [comment]
You are going to have to be more specific.  I just opened every single PDF within the repo and scrolled through them with zero issues, zero errors, etc.

**Comment by redguar** [comment]
You can close this, if you a click on the PDF... it gives the error. but then I use "download raw file" and it works.

**Comment by any2cards** [comment]
Now I understand ... you cannot view these PDFs while on-line ... they are too large ... this is controlled by GitHub.  You need to download them.
